name: OfflineTime
version: 1.0
main: com.foxsrv.offlinetime.OfflineTime
api-version: 1.20
depend: [Vault]

permissions:
  time.bypass:
    description: Imune ao sistema de perda de tempo offline
    default: op
